version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mysql_db
    environment:
       DB_HOST: mysql_db
       DB_PORT: 3306
       DB_USERNAME: root
       DB_PASSWORD: root
       DB_NAME: demo_db


  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_db

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: